;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Character.State.Movement.Crouch",NewTagName="Character.State.Movement.CrouchState")
+GameplayTagRedirects=(OldTagName="Character.State.Movement.JumpState.JumpingFromCrouch",NewTagName="Character.State.Movement.JumpState.JumpFromCrouch")
+GameplayTagList=(Tag="Character.State.Movement.CrouchState",DevComment="")
+GameplayTagList=(Tag="Character.State.Movement.CrouchState.AttemptUncrouch",DevComment="")
+GameplayTagList=(Tag="Character.State.Movement.CrouchState.CrouchIdle",DevComment="")
+GameplayTagList=(Tag="Character.State.Movement.CrouchState.CrouchJumping",DevComment="")
+GameplayTagList=(Tag="Character.State.Movement.CrouchState.CrouchResting",DevComment="")
+GameplayTagList=(Tag="Character.State.Movement.CrouchState.CrouchWalk",DevComment="")
+GameplayTagList=(Tag="Character.State.Movement.CrouchState.Slide",DevComment="")
+GameplayTagList=(Tag="Character.State.Movement.JumpState.JumpFromCrouch",DevComment="")
+GameplayTagList=(Tag="Character.State.Movement.JumpState.Jumping",DevComment="")
+GameplayTagList=(Tag="Character.State.Movement.JumpState.JumpNotPossible",DevComment="")
+GameplayTagList=(Tag="Character.State.Movement.JumpState.JumpPossible",DevComment="")
+GameplayTagList=(Tag="Character.State.Movement.Running",DevComment="")

